---
- name: Spin-up replayd on ubuntu server
  hosts: ubuntu
  gather_facts: False
  vars:
    golang_env:
      GOPATH: /home/ubuntu/Development/go
  become: yes
  tasks:
    - name: Install dependencies for replayd server
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      with_items:
        - golang-go
        - git
       # - go-dep
    - name: create required directories
      file:
        path: "{{item}}"
        state: directory
        mode: 0775
      with_items:
      - "{{ golang_env.GOPATH }}/src/github.com/souvikhaldar/"
      - "{{ golang_env.GOPATH }}/bin"
      - "/etc/replayd"
    
    - name: Copy config json file
      copy:
        src: ./config.json
        dest: /etc/replayd/
        mode: 0644

    - name: Synchronize source code
      synchronize:
        mode: push
        src: .
        dest: "{{golang_env.GOPATH}}/src/github.com/souvikhaldar/"
        

    - name: Install dep 
      shell: go get github.com/golang/dep/cmd/dep
      environment: "{{golang_env}}"
    
    - name: Synchronize dependencies
      shell: "{{ golang_env.GOPATH }}/bin/dep ensure"
      args:
        chdir: "{{golang_env.GOPATH}}/src/github.com/souvikhaldar/replayd/"
      environment: "{{golang_env}}"
    
    - name: Compile the server
      shell: go install
      args:
        chdir: "{{ golang_env.GOPATH }}/src/github.com/souvikhaldar/replayd/cmd/httpServer/"
      environment: "{{golang_env}}"

    - name: Copy unit file
      copy:
        src: ./replayd.service
        dest: /lib/systemd/system/
        mode: 0644

    - name: enable replayd service 
      shell: systemctl enable replayd.service
      args:
        chdir: "{{ golang_env.GOPATH }}/src/github.com/souvikhaldar/replayd"
      
    - name: start replayd service 
      shell: systemctl start replayd.service
      args:
        chdir: "{{ golang_env.GOPATH }}/src/github.com/souvikhaldar/replayd"

    - name: restart replayd service 
      shell: systemctl restart replayd.service
      args:
        chdir: "{{ golang_env.GOPATH }}/src/github.com/souvikhaldar/replayd"
    

      